# Generated by Django 2.2.5 on 2020-01-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplished', models.CharField(max_length=255)),
                ('working_on', models.CharField(max_length=255)),
                ('blocker', models.CharField(max_length=255)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standup.Standup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
