# Generated by Django 2.2 on 2019-04-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplished', models.CharField(max_length=255)),
                ('working_on', models.CharField(max_length=255)),
                ('blocker', models.CharField(max_length=255)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Standup')),
            ],
        ),
    ]
