# Generated by Django 2.2.5 on 2019-12-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standup',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='users',
        ),
    ]
