# Generated by Django 2.2 on 2019-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standup',
            name='date',
            field=models.DateTimeField(verbose_name='date of standup'),
        ),
    ]
