# Generated by Django 2.2 on 2019-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190421_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standup',
            name='date',
            field=models.DateTimeField(verbose_name='%Y-%d-%b'),
        ),
    ]
