# Generated by Django 2.2.1 on 2019-06-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190509_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
