# Generated by Django 2.2.5 on 2019-10-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='standup',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
            preserve_default=False,
        ),
    ]
